### ISSUE TITLE
build issues

### ISSUE THREAD

**Issue by alexmat** [jgarzik/pushpool#13]
I'm getting this when I try to build:

gcc -DHAVE_CONFIG_H -I. -fno-strict-aliasing -pthread -I/usr/include/mysql -fPIC -pipe -fno-strict-aliasing -DBIG_JOINS=1 -fomit-frame-pointer  -g -I/usr/include    -g -O2 -MT config.o -MD -MP -MF .deps/config.Tpo -c -o config.o config.c
config.c: In function ‘read_config’:
config.c:305:2: warning: passing argument 2 of ‘json_loads’ makes integer from pointer without a cast [enabled by default]
/usr/include/jansson.h:219:9: note: expected ‘size_t’ but argument is of type ‘struct json_error_t _’
config.c:305:2: error: too few arguments to function ‘json_loads’
/usr/include/jansson.h:219:9: note: declared here
make[1]: *_\* [config.o] Error 1

Any suggestions on where the problem may be? Is it my jansson library version (2.0.1)?

**Comment by alexmat** [comment]
Looks like a placeholder parameter was added:

"Add a flags parameter to all decoding functions for future needs

As of now, the parameter is unused, but may be needed in the future.
I'm adding it now so that in the future both API and ABI remain
backwards compatible as long as possible.

This is a backwards incompatible change."

https://github.com/akheron/jansson/commit/bfac1972e25b40f849852ce3c10e0a8ad47f79d7

**Comment by jgarzik** [comment]
You need jansson 1.x to build
