### ISSUE TITLE
Configure script fails

### ISSUE THREAD

**Issue by lukebeer** [jgarzik/pushpool#28]
% SNIP %
checking for SQLite3 library >= 3.0.0... yes
checking for mysql_config... /usr/bin/mysql_config
checking for pg_config... no
no
./configure: line 5958: syntax error near unexpected token `,'
./configure: line 5958:`LIBCURL_CHECK_CONFIG(, 7.10.1, ,'
-bash-3.2$ 

Line 5958:
LIBCURL_CHECK_CONFIG(, 7.10.1, ,
  AC_MSG_ERROR([Missing required libcurl >= 7.10.1]))

Unless I'm doing something wrong?!

Version 0.5 (3 days ago)

Many Thanks!

**Comment by jgarzik** [comment]
FAQ: use the release tarball, your system is not properly generating configure scripts

**Comment by marcusrbrown** [comment]
I submitted a pull request that fixes this:
https://github.com/jgarzik/pushpool/pull/31
