### ISSUE TITLE
autotools-config.h Missing.

### ISSUE THREAD

**Issue by ghost** [jgarzik/pushpool#47]
Using the Vs2012 Developer console:

C:\Users\Elycin\Documents>cd pushpool-master

C:\Users\Elycin\Documents\pushpool-master>cl server.c
Microsoft (R) C/C++ Optimizing Compiler Version 17.00.50727.1 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

server.c
server.c(24) : fatal error C1083: Cannot open include file: 'autotools-config.h
: No such file or directory

**Comment by jgarzik** [comment]
This is an auto-generated file.  You need to run autogen.sh and then configure, which is not directly supported in Windows.
