### ISSUE TITLE
pushpool not insert difficulty to shares table 

### ISSUE THREAD

**Issue by saymissme** [jgarzik/pushpool#54]
i am running a pushpool for one coin
and set "rpc.target.bits" : 32, in my server.json
the working diff is 1.
every thing is working fine

but pushpool insert sharelog to my mysql database without difficulty info
i need more difficulty port

do you know hwo to fix it?
@jgarzik @ahmedbodi @electricintel @girino

**Comment by electricintel** [comment]
http://bitcoin.stackexchange.com/questions/4303/how-to-setup-pushpool
http://stackoverflow.com/questions/15573697/json-call-to-mysql-improperly-handling-variable
There was a working pushpool json file in an earlier how to online, I'll see if I can find it.

**Comment by electricintel** [comment]
Try this new configuration:
Terminal installation instructions!
http://pastebin.com/YUYz0W5B

**Comment by saymissme** [comment]
thanks for your reply
my pushpool is working fine
the json config file is ok

i want use other config file and pid to running another diff port
but not insert difficulty to shares table 

i will try change code for support it
thank you very much

**Comment by electricintel** [comment]
Send a copy of your pushpool  and *.json and I'll help or fork it on Github
and I can really help!

Philip

**Comment by saymissme** [comment]
thank you very much
i was use this https://github.com/ArtForz/pushpool
set json like this
easy difficulty 1 

```
`{
        "listen" : [.....],
    "database" : {
        "engine" : "mysql",
        ..................
        "stmt.pwdb":"SELECT `password` FROM `pool_worker` WHERE `username` = ?",
        "stmt.sharelog":"INSERT INTO shares (rem_host, username, our_result, upstream_result, reason, solution) VALUES (?, ?, ?, ?, ?, ?)"
    },
    .........................

    "rpc.target.bits" : 32,
}`
```

set easy difficulty to 2, like this
`"rpc.target.bits" : 33,`

set easy difficulty to 4, like this
`"rpc.target.bits" : 34,`

use those command to start different port difficulty and pid  daemon

```
/pushpoold -E -F --config=1.json
/pushpoold -E -F --config=2.json
/pushpoold -E -F --config=4.json
```

but pushpool couldnt insert different to shares table
need fix it

**Comment by electricintel** [comment]
I'm doing some software work for a client at the moment and won't be online
much, but I'll send you what information that I can in my spare time.

Philip

**Comment by jgarzik** [comment]
closed - obsolete software - not actively supported or maintained.
